// Добавить новые сущности аналогично в MetaType.ts

// Model
export * from './AbstarctDictionary'
export * from './AbstractDemand'
export * from './AbstractFile'
export * from './AbstractGood'
export * from './AbstractReturn'
export * from './Account'
export * from './Address'
export * from './Agent'
export * from './AgentNote'
export * from './Assortment'
export * from './Attribute'
export * from './Barcode'
export * from './CashIn'
export * from './CashOut'
export * from './Characteristic'
export * from './Collection'
export * from './CollectionRef'
export * from './Company'
export * from './CompanySettings'
export * from './ContactPerson'
export * from './Contract'
export * from './Counterparty'
export * from './Currency'
export * from './CustomEntity'
export * from './CustomerOrder'
export * from './CustomerOrderPosition'
export * from './Demand'
export * from './DemandPosition'
export * from './Discount'
export * from './Document'
export * from './DocumentWithPositions'
export * from './Employee'
export * from './Entity'
export * from './EntityRef'
export * from './File'
export * from './Group'
export * from './HasAddress'
export * from './HasAttributes'
export * from './HasCreated'
export * from './HasDeleted'
export * from './HasFiles'
export * from './HasProject'
export * from './HasState'
export * from './HasStore'
export * from './HasUpdated'
export * from './HasVat'
export * from './Id'
export * from './Image'
export * from './Inventory'
export * from './InventoryPosition'
export * from './Invoice'
export * from './InvoiceIn'
export * from './InvoiceOut'
export * from './InvoicePosition'
export * from './Legal'
export * from './MediaType'
export * from './Meta'
export * from './Metadata'
export * from './MetaType'
export * from './MoyskladObject'
export * from './Order'
export * from './Organization'
export * from './Owned'
export * from './Pack'
export * from './PaymentIn'
export * from './PaymentOut'
export * from './Person'
export * from './Position'
export * from './Price'
export * from './PriceType'
export * from './Product'
export * from './ProductFolder'
export * from './Rate'
export * from './RetailDemand'
export * from './RetailSalesReturn'
export * from './SalePrice'
export * from './SalesReturn'
export * from './SalesReturnPosition'
export * from './Slot'
export * from './State'
export * from './Store'
export * from './StoreZone'
export * from './TaxSystem'
export * from './Uom'
export * from './Variant'

// Utility types
export * from './utils'

// Reports
export * from './reports'

// API
export * from './api'
